$f = 'd:\ESWAR\happy-helper\src\pages\DealCenter.tsx'
$c = [System.IO.File]::ReadAllText($f)
$c = $c.Replace('bg-[#FAF7F2]', 'bg-background')
$c = $c.Replace('text-[#1F2937]', 'text-foreground')
$c = $c.Replace('border-[#E5E7EB]', 'border-border')
$c = $c.Replace('hover:border-slate-300', 'hover:border-border/80')
$c = $c.Replace('bg-white/80', 'bg-card/80')
$c = $c.Replace('bg-white', 'bg-card')
$c = $c.Replace('text-slate-700', 'text-foreground')
$c = $c.Replace('text-slate-600', 'text-muted-foreground')
$c = $c.Replace('text-slate-500', 'text-muted-foreground')
$c = $c.Replace('text-slate-400', 'text-muted-foreground')
$c = $c.Replace('bg-indigo-50', 'bg-primary/10')
$c = $c.Replace('bg-slate-50', 'bg-secondary')
$c = $c.Replace('from-white to-slate-50', 'from-card to-secondary')
$c = $c.Replace('from-card to-secondary', 'from-card to-secondary')
$c = $c.Replace('hover:bg-slate-200', 'hover:bg-secondary')
[System.IO.File]::WriteAllText($f, $c)
Write-Host "Done! DealCenter.tsx tokens migrated."
