{
  "name": "innovestor-supabase-proxy",
  "main": "index.ts",
  "compatibility_date": "2024-09-23",
  "compatibility_flags": ["nodejs_compat"],

  "vars": {
    "SUPABASE_TARGET_URL": "https://wxnxmglyularlfughmen.supabase.co"
  }
}
